Fixed target names in CI\CD

diff --git a/.github/workflows/ci_tests.yml b/.github/workflows/ci_tests.yml
--- a/.github/workflows/ci_tests.yml
+++ b/.github/workflows/ci_tests.yml
@@ -68,12 +68,12 @@ jobs:
       - name: Build main target
         shell: bash
         run: |
-          cmake --build cmake-build-release --target cpp_tests || echo "Built with errors"
+          cmake --build cmake-build-release --target weather_forecast || echo "Built with errors"
 
       - name: Build tests target
         shell: bash
         run: |
-          cmake --build cmake-build-debug --target cpp_tests_tests || echo "Built with errors"
+          cmake --build cmake-build-debug --target weather_forecast_tests || echo "Built with errors"
 
       - name: Run program
         shell: bash
@@ -81,14 +81,14 @@ jobs:
         run: |
           if [ "$RUNNER_OS" == "Windows" ]; then
               if [ "${{ matrix.config.cxx }}" == "g++" ]; then
-                ./cpp_tests.exe --help
+                ./weather_forecast.exe --help
               else
                 cd Debug
-                ./cpp_tests.exe --help
+                ./weather_forecast.exe --help
               fi
           else 
               cd bin
-              ./cpp_tests --help
+              ./weather_forecast --help
           fi
 
       - name: Run tests
@@ -97,14 +97,14 @@ jobs:
         run: |
           if [ "$RUNNER_OS" == "Windows" ]; then
               if [ "${{ matrix.config.cxx }}" == "g++" ]; then
-                ./cpp_tests_tests_.exe
+                ./weather_forecast_tests_.exe
               else
                 cd Debug
-                ./cpp_tests_tests.exe
+                ./weather_forecast_tests.exe
               fi
           else
               cd tests
-              ./cpp_tests_tests
+              ./weather_forecast_tests
           fi
 
   memory-leaks:
